### ISSUE TITLE
Setup page not available after creating fresh fleet and fleet-database instances

### ISSUE THREAD

**Issue by Griefed** [linuxserver/docker-fleet#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When creating a fresh fleet-instance via docker-fleet, the setup page should be available at `http:<IP>:<PORT>/setup`

## Current Behavior

Visiting `http:<IP>:<PORT>/setup` after creating the fleet and fleet-database containers results in a page displaying `Not found` 

Directories exist/are created and have the correct IDs.

## Steps to Reproduce

1. Add the services from the `## Command used to create docker container (run/create/compose/screenshot)`-section below
2. Run ``docker-compose up -d fleet fleetdb`
3. Browse to `http:<IP>:<PORT>/setup`
4. Observe page only displaying `Not found`

## Environment
**OS:** Ubuntu 20.04.5 LTS
**CPU architecture:** x86_64
**How docker service was installed:** Using the get-docker script at `https://get.docker.com/`, running `apt-get install docker-compose -y` afterwards

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d fleet fleetdb`

```yaml
  fleet:
    image: ghcr.io/linuxserver/fleet:2.3.3-ls128
    container_name: fleet
    restart: unless-stopped
    ports:
      - 9090:8080
    volumes:
      - ./services/fleet/config:/config
    depends_on:
      - fleetdb
    networks:
      - default
    environment:
      - PUID=1003
      - PGID=998
      - TZ=Europe/Berlin
      - fleet_admin_authentication_type=DATABASE
      - fleet_database_url=jdbc:mariadb://fleetdb:3306/fleet
      - fleet_database_username=******
      - fleet_database_password=******
      - fleet_admin_secret=******
  fleetdb:
    image: ghcr.io/linuxserver/mariadb:10.6.10-r0-ls72
    container_name: fleetdb
    restart: unless-stopped
    volumes:
      - ./services/fleet/db:/config
    networks:
      - default
    environment:
      - PUID=1003
      - PGID=998
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=******
      - MYSQL_DATABASE=fleet
      - MYSQL_USER=******
      - MYSQL_PASSWORD=******
```

## Docker logs

```
[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1003
User gid:    998
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/19-armless
cont-init: info: /etc/cont-init.d/19-armless exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun fleet (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
```
